src/zAssignment3 Practice/Assignment 2 Full/DevSkill.Inventory/DevSkill.Inventory.Web/Areas/Admin/Models/BlogPostCreateModel.cs
namespace DevSkill.Inventory.Web.Areas.Admin.Models
{
    public class BlogPostCreateModel
    {
        public string Title { get; set; }
    }
}

src/zAssignment3 Practice/Assignment 2 Full/DevSkill.Inventory/DevSkill.Inventory.Web/Areas/Admin/Models/DashboardModel.cs
namespace DevSkill.Inventory.Web.Areas.Admin.Models
{
    public class DashboardModel
    {
    }
}

src/zAssignment3 Practice/Assignment 2 Full/DevSkill.Inventory/DevSkill.Inventory.Web/Models/DashboardModel.cs
namespace DevSkill.Inventory.Web.Models
{
    public class DashboardModel
    {
    }
}

src/zAssignment3 Practice/Assignment 2 Full/DevSkill.Inventory/DevSkill.Inventory.Web/Models/ErrorViewModel.cs
namespace DevSkill.Inventory.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/zAssignment3 Practice/Assignment 2 Full/DevSkill.Inventory/DevSkill.Inventory.Web/Areas/Admin/Controllers/BlogPostController.cs
using Blog.Domain.Entities;
using Blog.Application.Services;
using DevSkill.Inventory.Web.Areas.Admin.Models;
using Microsoft.AspNetCore.Mvc;

namespace DevSkill.Inventory.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class BlogPostController : Controller
    {
        private readonly IBlogPostManagementServices _blogPostManagementServices;
        public BlogPostController(IBlogPostManagementServices blogPostManagementServices)
        {
            _blogPostManagementServices = blogPostManagementServices;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult Create(BlogPostCreateModel model)
        {
            if (ModelState.IsValid) 
            {
                var blog = new BlogPost { Id = Guid.NewGuid(), Title = model.Title };
                _blogPostManagementServices.CreateBlogPost(blog);
                return RedirectToAction("Index");
            }

            return View();
        }
    }
}

src/zAssignment3 Practice/Assignment 2 Full/DevSkill.Inventory/DevSkill.Inventory.Web/Areas/Admin/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;

namespace DevSkill.Inventory.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class DashboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/zAssignment3 Practice/Assignment 2 Full/DevSkill.Inventory/DevSkill.Inventory.Web/Controllers/HomeController.cs
using DevSkill.Inventory.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace DevSkill.Inventory.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
           
        }

        public IActionResult Index()
        {
            _logger.LogInformation("in index");
            return View();
        }

        public IActionResult Privacy()
        {
            _logger.LogInformation("in Privacy");
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/zAssignment3 Practice/Assignment 2 Full/DevSkill.Inventory/DevSkill.Inventory.Web/Areas/Admin/Views/BlogPost/Create.cshtml
@model BlogPostCreateModel
@{
    ViewData["Title"] = "Create";
}

    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Create New Post</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Blog Posts</a></li>
              <li class="breadcrumb-item active">Create New</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <!-- left column -->
          <div class="col-md-6">
            <!-- general form elements -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Write a Post</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form asp-antiforgery="true" asp-area="Admin" asp-controller="BlogPost" asp-action="Create" method="post">
                <div class="card-body">
                  <div class="form-group">
                    <label asp-for="Title">Title</label>
                    <input type="text" asp-for="Title" class="form-control" >
                  </div>
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </form>
            </div>
            <!-- /.card -->
          </div>
          <!--/.col (left) -->

        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->

src/zAssignment3 Practice/Assignment 2 Full/DevSkill.Inventory/DevSkill.Inventory.Web/Areas/Admin/Views/BlogPost/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

src/zAssignment3 Practice/Assignment 2 Full/DevSkill.Inventory/DevSkill.Inventory.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

src/zAssignment3 Practice/Assignment 2 Full/DevSkill.Inventory/DevSkill.Inventory.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DevSkill.Inventory.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DevSkill.Inventory.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DevSkill.Inventory.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - DevSkill.Inventory.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>